### ISSUE TITLE
some manual maybe?

### ISSUE THREAD

**Issue by cosmolabs-ru** [shariltumin/tscp#1]
Not a great pleasure to read obfuscated code.
why not write at least basic guidelines to deployment of this into a real project?
You should include and example -- (test cases are not examples) --
which shows how to:

- generate a keypair
- generate a symmetric key from my/theirs keys

If it's just a scientific work, and you don't care how others would use it - keep it in your table, and don't waste users' time and Github's disk space.

**Comment by shariltumin** [comment]
I am sorry that you wasted your time and found that the contents of this repository were not to your liking. You are free to express your opinion, but if you are frustrated that you have found nothing useful here, please do not take it out on me.  You are free to look around or go elsewhere.

I am free to put anything in my repository, and the only thing that can stop me from doing so is Github, but not from the likes of you.

How I write my code and what I share with the community is up to me. I do not owe you an explanation. It is fine if you think it is all nonsense, others may feel differently.
